# Generated by Django 3.0.7 on 2020-06-06 17:20

from django.db import migrations, models
import django.db.models.deletion
import sja.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Detection Name')),
                ('model_name', models.CharField(choices=[('fasterrcnn_resnet50_fpn_cocotrained', 'Faster R-CNN ResNet 50 FPN Model Trained on COCO dataset')], default='fasterrcnn_resnet50_fpn_cocotrained', max_length=100)),
                ('input_file', models.FileField(upload_to=sja.models.defect_upload_location)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=sja.models.image_upload_location, width_field='width')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('detection_bounding_boxes', models.TextField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sja.Detection')),
            ],
        ),
    ]
