# Generated by Django 3.0.7 on 2020-06-06 18:38

import django.core.validators
from django.db import migrations, models
import sja.models


class Migration(migrations.Migration):

    dependencies = [
        ('sja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='input_file',
            field=models.FileField(upload_to=sja.models.defect_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'jpg', 'png'])]),
        ),
    ]
