# Generated by Django 3.0.7 on 2020-06-07 10:20

import django.core.validators
from django.db import migrations, models
import sja.models


class Migration(migrations.Migration):

    dependencies = [
        ('sja', '0004_auto_20200607_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='input_file',
            field=models.FileField(upload_to=sja.models.defect_upload_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to=sja.models.image_upload_location, width_field='width'),
        ),
    ]
